#!/usr/bin/env bash
if [[ $# -eq 1 ]]; then
	sigcheck_exe=/cygdrive/d/Dropbox/Myfiles/win/Downloads/software/sys/SysinternalsSuite/sigcheck.exe
	file_path="$(cygpath -aw "$1")"
	"$sigcheck_exe" "$file_path" |iconv -f gbk -t utf-8
fi
